### ISSUE TITLE
不生效啊。

### ISSUE THREAD

**Issue by cancundeyingzi** [Xposed-Modules-Repo/xyz.ccat3z.nodisplaycutout#2]
比方说导倒置过来，下面那一条还是黑的。又或者说电源键朝下横屏过来。右边还是不显示内容。

**Comment by cancundeyingzi** [comment]
老色批日志文件https://cancundeyingzi.xyz/%E5%BA%A6%E7%9B%98%E4%BB%A3%E4%B8%8B/%E9%98%BF%E9%87%8C%E4%BA%91%E5%88%86%E4%BA%AB/LSPosed_2022-08-25T13_15_52.434.zip

**Comment by cancundeyingzi** [comment]
测试的一个是b站(修改包名版本)，一个是酷安。

**Comment by ccat3z** [comment]
建议用这个Magisk模块: https://github.com/MlgmXyysd/NoneDisplayCutout. 这个Xposed插件生效条件有限.

**Comment by cancundeyingzi** [comment]
> 建议用这个Magisk模块: https://github.com/MlgmXyysd/NoneDisplayCutout. 这个Xposed插件生效条件有限.

感谢已经用上了,生效
